
POST http://flip3.engr.oregonstate.edu:11785/passengers/add HTTP/1.1
content-type: application/json

{
    "firstName": "Test", 
    "lastName": "Tester", 
    "passport": "637071711", 
    "email": "test@gmail.com", 
    "phoneNumber":"318-234-3554"
}

###
DELETE http://flip3.engr.oregonstate.edu:11785/flights/3 HTTP/1.1

###
PUT http://flip2.engr.oregonstate.edu:11785/flights/2 HTTP/1.1
Content-Type: application/json

{
    "departure_airport": "KLGA",
    "arrival_airport": "RJAA",
    "departure_time": "STR_TO_DATE('2022-11-19T23:03' '%Y%m%d %H%i')",
    "arrival_time": "CAST('2022-11-19T23:07' AS datetime)",
    "air_fare": 20000,
    "capacity": 1000
}
