
POST http://flip3.engr.oregonstate.edu:11785/passengers/add HTTP/1.1
content-type: application/json

{
    "firstName": "Test", 
    "lastName": "Tester", 
    "passport": "637071711", 
    "email": "test@gmail.com", 
    "phoneNumber":"318-234-3554"
}

###
DELETE http://flip3.engr.oregonstate.edu:11785/flights/3 HTTP/1.1

###
POST http://flip2.engr.oregonstate.edu:11789/booking/add HTTP/1.1
Content-Type: application/json

{
    "passenger_id": 1,
    "tripName": "Test Trip",
    "ticketClass": 2,
    "flightChoices": [2, 3]
}
